import json
import os
import re

import google.generativeai as genai


FOCUS = {
    "balance_sheet": "assets, liabilities, equity, liquidity, debt position, and financial stability",
    "trial_balance": "debit and credit balances, large balances, unusual accounts, expense concentration, and income concentration",
    "profit_and_loss": "revenue, expenses, profitability, cost increases, margin, and net profit or loss",
    "income_expense": "income sources, expense heads, surplus or deficit, cost control, and sustainability",
}


def _fallback_insights(statement_type, data):
    summary = data.get("summary", {})
    analytics = data.get("analytics", {})
    
    def fmt(val):
        if val is None:
            return "N/A"
        try:
            return f"{float(val):,.2f}"
        except (ValueError, TypeError):
            return str(val)

    cb = analytics.get("cash_and_bank", {}).get("value")
    wc = analytics.get("working_capital", {}).get("value")
    rec = analytics.get("receivables", {}).get("value")
    pay = analytics.get("payables", {}).get("value")
    fa = analytics.get("fixed_assets", {}).get("value")
    inv = analytics.get("investments", {}).get("value")

    inc_val = summary.get("total_income", 0) or 0
    exp_val = summary.get("total_expenses", 0) or 0

    top_income_list = analytics.get("largest_income_accounts") or []
    top_expense_list = analytics.get("largest_expense_accounts") or []
    top_income = top_income_list[0] if top_income_list else None
    top_expense = top_expense_list[0] if top_expense_list else None

    return [
        f"**Executive Summary**: This is a {statement_type.replace('_', ' ')} statement. Total assets are {fmt(summary.get('total_assets'))} and total equity (society's share) is {fmt(summary.get('equity'))}.",
        f"**Liquidity Analysis**: Cash & bank balance is {fmt(cb)}. Money owed to the society (receivables) is {fmt(rec)}, and money the society owes (payables) is {fmt(pay)}.",
        f"**Asset Analysis**: Fixed assets (like property, equipment) are worth {fmt(fa)}, and long-term investments are worth {fmt(inv)}.",
        f"**Income Analysis**: Total income earned in this period is {fmt(inc_val)}.",
        f"**Expense Analysis**: Total expenses spent in this period are {fmt(exp_val)}.",
        (
            f"**Highest Income Source**: The biggest source of income is \"{top_income['account']}\", contributing {fmt(top_income['value'])}."
            if top_income else "**Highest Income Source**: No income accounts found."
        ),
        (
            f"**Highest Expense**: The biggest expense is \"{top_expense['account']}\", costing {fmt(top_expense['value'])}."
            if top_expense else "**Highest Expense**: No expense accounts found."
        ),
        f"**Risk Observations**: Net working capital (short-term funds available) is {fmt(wc)}. This should be watched closely to make sure day-to-day bills can be paid on time.",
        f"**Business Recommendations**: Keep an eye on payables of {fmt(pay)} and try to collect receivables of {fmt(rec)} faster to keep enough cash on hand for the society."
    ]


def _parse_bullets(text):
    points = []
    for line in text.splitlines():
        cleaned = re.sub(r"^\s*(?:[-*•]|\d+[.)])\s*", "", line).strip()
        if cleaned:
            points.append(cleaned)
    return points


MIN_VALID_POINTS = 7


def generate_financial_insights(statement_type, financial_data):
    """Return exactly 9-10 insights generated by Gemini; only falls back to a local
    rule-based summary if Gemini is unreachable or returns too little to be usable."""
    fallback = _fallback_insights(statement_type, financial_data)
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("Gemini generation skipped: GEMINI_API_KEY is not set")
        return fallback[:10]

    filtered_data = {
        "summary": financial_data.get("summary", {}),
        "analytics": financial_data.get("analytics", {})
    }

    prompt = f"""
You are an accountant explaining this {statement_type.replace('_', ' ')} financial statement to the
committee members of a housing society who have no accounting background. This statement belongs
to the society, not to a private business — always refer to it as "the society" or "the society's"
(never "your business" or "the company"). Write in plain, everyday language — avoid technical
jargon, and where a technical term is unavoidable, briefly explain it in simple words in the same
sentence.

Provide exactly one bullet point for each of the following sections, in order:
• **Executive Summary**
• **Liquidity Analysis**
• **Asset Analysis**
• **Income Analysis**
• **Expense Analysis**
• **Highest Income Source**
• **Highest Expense**
• **Risk Observations**
• **Business Recommendations**

Guidelines:
- Return exactly 9-10 concise bullet points in total, using prefix format: '• **[Section Name]**: [Insight]'
- Use the actual numbers from the data below wherever relevant (e.g. "cash is 1,50,000") so the
  reader can see the figures, not just a vague description.
- For "Highest Income Source" and "Highest Expense", name the specific account with the largest
  value from the largest_income_accounts / largest_expense_accounts lists and state its amount.
- Do NOT perform any mathematical calculations of your own. Use only the supplied pre-calculated values.
- Do NOT make assumptions or invent numbers.
- Do NOT include intro/outro text or markdown headers outside the bullet points.
- Keep sentences short and simple, like explaining to a friend, not writing a formal audit report.
- Do NOT mention or evaluate Net Result.

Pre-calculated financial data:
{json.dumps(filtered_data, default=str, indent=2)}
"""
    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content(prompt, request_options={"timeout": 30})
        points = _parse_bullets(response.text)
        if len(points) < MIN_VALID_POINTS:
            print(f"Gemini returned too few points ({len(points)}), using fallback")
            return fallback[:10]
        return points[:10]
    except Exception as exc:
        print("Gemini generation failed, using fallback:", exc)
        return fallback[:10]
